image: google/cloud-sdk:alpine

deploy_production:
  stage: deploy
  environment: Production
  only:
  - master
  script:
  - echo $SERVICE_ACCOUNT > /tmp/$CI_PIPELINE_ID.json
  - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
  - gsutil -m rsync -d -R src/ gs://www.ejdyksen.com

after_script:
- rm /tmp/$CI_PIPELINE_ID.json
