image: google/cloud-sdk:alpine

deploy_production:
  stage: deploy
  environment: Production
  only:
  - master
  script:
  - echo $SERVICE_ACCOUNT > /tmp/$CI_PIPELINE_ID.json
  - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
  - gsutil -m rsync -d -R src/ gs://www.ejdyksen.com

deploy_review:
  stage: deploy
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://www.ejdyksen.com/$CI_ENVIRONMENT_SLUG/
    on_stop: stop_review
  only:
  - branches
  except:
  - master
  script:
  - echo $SERVICE_ACCOUNT > /tmp/$CI_PIPELINE_ID.json
  - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
  - gsutil -m rsync -d -R src/ gs://www.ejdyksen.com/$CI_ENVIRONMENT_SLUG/

stop_review:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  when: manual
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop
  script:
  - echo $SERVICE_ACCOUNT > /tmp/$CI_PIPELINE_ID.json
  - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
  - gsutil -m rm -r gs://www.ejdyksen.com/$CI_ENVIRONMENT_SLUG

after_script:
- rm /tmp/$CI_PIPELINE_ID.json
